the crazy error message nobody asked for
error: expression too complex to compile
   ┌─ lol2.anm.spec:27:48
   │
27 │     if ((I0 + 2) * ((I0 + 4) - 3) == (I0*I0) * (I0+1)) goto end;
   │         -------------------------    ----------^^^^^^
   │         │                            │         │
   │         │                            │         no more registers of this type!
   │         │                            I3 holds this
   │         I1 holds this
   │
   = the following registers are unavailable due to explicit use: I0, I2, I4, I5